/**
 * @author Ignacio
 * Jose Ignacio Herrera Martinez
 * 201356054
 * 3743 - Ingenieria de Sistemas
 * Universidad del Valle
 */

package display;

import logic.CalculatorLogic;

public class CalculatorDisplay extends javax.swing.JFrame {
    
    private CalculatorLogic calculator = new CalculatorLogic();
    /**
     * Creates new form CalculatorDisplay
     */
    public CalculatorDisplay() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Calculator");
        this.setResizable(false);
        CalculatorLogic calculator = new CalculatorLogic();
        
        //*********************************************PRUEBA_INICIO
        System.out.println("AQUI LA PRUEBA");
        //*********************************************PRUEBA_FIN
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCalc = new javax.swing.JPanel();
        jLabelCalc = new javax.swing.JLabel();
        jButtonTwo = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonEight = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonSquare = new javax.swing.JButton();
        jButtonSubtract = new javax.swing.JButton();
        jButtonSquareRoot = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonMemoryMinus = new javax.swing.JButton();
        jButtonMemory = new javax.swing.JButton();
        jButtonMemoryRecall = new javax.swing.JButton();
        jButtonMemoryClear = new javax.swing.JButton();
        jTextFieldCalc = new javax.swing.JTextField();
        jButtonClearError = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jTextFieldCalcPast = new javax.swing.JTextField();
        jLabelMemory = new javax.swing.JLabel();
        jLabelMemoryValue = new javax.swing.JLabel();
        jLabelOperation = new javax.swing.JLabel();
        jButtonEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCalc.setBackground(new java.awt.Color(0, 0, 0));

        jLabelCalc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelCalc.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCalc.setText("CALCULATOR");

        jButtonTwo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTwo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonTwo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTwo.setText("2");
        jButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwoActionPerformed(evt);
            }
        });

        jButtonThree.setBackground(new java.awt.Color(0, 0, 0));
        jButtonThree.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonThree.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThree.setText("3");
        jButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThreeActionPerformed(evt);
            }
        });

        jButtonFour.setBackground(new java.awt.Color(0, 0, 0));
        jButtonFour.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonFour.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFour.setText("4");
        jButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFourActionPerformed(evt);
            }
        });

        jButtonFive.setBackground(new java.awt.Color(0, 0, 0));
        jButtonFive.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonFive.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFive.setText("5");
        jButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiveActionPerformed(evt);
            }
        });

        jButtonSix.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSix.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSix.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSix.setText("6");
        jButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSixActionPerformed(evt);
            }
        });

        jButtonOne.setBackground(new java.awt.Color(0, 0, 0));
        jButtonOne.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonOne.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOne.setText("1");
        jButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneActionPerformed(evt);
            }
        });

        jButtonEight.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonEight.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEight.setText("8");
        jButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEightActionPerformed(evt);
            }
        });

        jButtonNine.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonNine.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNine.setText("9");
        jButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNineActionPerformed(evt);
            }
        });

        jButtonSeven.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSeven.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSeven.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeven.setText("7");
        jButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSevenActionPerformed(evt);
            }
        });

        jButtonZero.setBackground(new java.awt.Color(0, 0, 0));
        jButtonZero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonZero.setForeground(new java.awt.Color(255, 255, 255));
        jButtonZero.setText("0");
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });

        jButtonMultiply.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMultiply.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonMultiply.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultiply.setText("X");
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDivide.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDivide.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonDivide.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivide.setText("/");
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });

        jButtonSquare.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSquare.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonSquare.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSquare.setText("x^2");
        jButtonSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSquareActionPerformed(evt);
            }
        });

        jButtonSubtract.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSubtract.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSubtract.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubtract.setText("-");
        jButtonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtractActionPerformed(evt);
            }
        });

        jButtonSquareRoot.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSquareRoot.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSquareRoot.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSquareRoot.setText("√2");
        jButtonSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSquareRootActionPerformed(evt);
            }
        });

        jButtonPlus.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPlus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlus.setText("M+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonMemoryMinus.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMemoryMinus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonMemoryMinus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMemoryMinus.setText("M-");
        jButtonMemoryMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoryMinusActionPerformed(evt);
            }
        });

        jButtonMemory.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMemory.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonMemory.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMemory.setText("M");
        jButtonMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoryActionPerformed(evt);
            }
        });

        jButtonMemoryRecall.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMemoryRecall.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMemoryRecall.setText("MR");
        jButtonMemoryRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoryRecallActionPerformed(evt);
            }
        });

        jButtonMemoryClear.setBackground(new java.awt.Color(0, 0, 0));
        jButtonMemoryClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMemoryClear.setText("MC");
        jButtonMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoryClearActionPerformed(evt);
            }
        });

        jTextFieldCalc.setEditable(false);
        jTextFieldCalc.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldCalc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldCalc.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCalc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCalc.setText("0");

        jButtonClearError.setBackground(new java.awt.Color(0, 0, 0));
        jButtonClearError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonClearError.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClearError.setText("CE");
        jButtonClearError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearErrorActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(0, 0, 0));
        jButtonClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTextFieldCalcPast.setEditable(false);
        jTextFieldCalcPast.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldCalcPast.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldCalcPast.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCalcPast.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCalcPast.setText("0");

        jLabelMemory.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMemory.setText("Memory:");

        jLabelMemoryValue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMemoryValue.setText("0");

        jLabelOperation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOperation.setText("...");

        jButtonEqual.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEqual.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonEqual.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEqual.setText("=");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCalcLayout = new javax.swing.GroupLayout(jPanelCalc);
        jPanelCalc.setLayout(jPanelCalcLayout);
        jPanelCalcLayout.setHorizontalGroup(
            jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcLayout.createSequentialGroup()
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jLabelCalc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCalcPast, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelCalcLayout.createSequentialGroup()
                                    .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                                            .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                                            .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanelCalcLayout.createSequentialGroup()
                                                    .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                                            .addComponent(jLabelMemory)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabelMemoryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalcLayout.createSequentialGroup()
                                                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButtonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(8, 8, 8)
                                                        .addComponent(jButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalcLayout.createSequentialGroup()
                                                        .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButtonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButtonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanelCalcLayout.createSequentialGroup()
                                                    .addGap(2, 2, 2)
                                                    .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                                                            .addComponent(jButtonMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonMemoryMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                                                            .addComponent(jButtonMemoryRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jButtonClearError, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGroup(jPanelCalcLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelCalcLayout.setVerticalGroup(
            jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCalcPast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOperation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalcLayout.createSequentialGroup()
                        .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCalcLayout.createSequentialGroup()
                        .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMemoryMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMemoryRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearError, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMemory)
                        .addComponent(jLabelMemoryValue)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("1");
    }//GEN-LAST:event_jButtonOneActionPerformed

    private void jButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwoActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("2");
    }//GEN-LAST:event_jButtonTwoActionPerformed

    private void jButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThreeActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("3");
    }//GEN-LAST:event_jButtonThreeActionPerformed

    private void jButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFourActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("4");
    }//GEN-LAST:event_jButtonFourActionPerformed

    private void jButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiveActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("5");
    }//GEN-LAST:event_jButtonFiveActionPerformed

    private void jButtonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSixActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("6");
    }//GEN-LAST:event_jButtonSixActionPerformed

    private void jButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSevenActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("7");
    }//GEN-LAST:event_jButtonSevenActionPerformed

    private void jButtonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEightActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("8");
    }//GEN-LAST:event_jButtonEightActionPerformed

    private void jButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNineActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("9");
    }//GEN-LAST:event_jButtonNineActionPerformed

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        // TODO add your handling code here:
        addTextToFieldCalc("0");
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonClearErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearErrorActionPerformed
        // TODO add your handling code here:
        initializeFieldCalc();
    }//GEN-LAST:event_jButtonClearErrorActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        initializeFieldCalc();
        initializeFieldCalcPast();
        initializeLabelOperation();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        
        if(verifyPendingOperation()){
            SolveOperation();
        }
        
        jLabelOperation.setText("+");
        jTextFieldCalcPast.setText(jTextFieldCalc.getText());
        initializeFieldCalc();
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        SolveOperation();
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtractActionPerformed
        // TODO add your handling code here:
        if(verifyPendingOperation()){
            SolveOperation();
        }
        
        jLabelOperation.setText("-");
        jTextFieldCalcPast.setText(jTextFieldCalc.getText());
        initializeFieldCalc();
    }//GEN-LAST:event_jButtonSubtractActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        // TODO add your handling code here:
        if(verifyPendingOperation()){
            SolveOperation();
        }
        
        jLabelOperation.setText("X");
        jTextFieldCalcPast.setText(jTextFieldCalc.getText());
        initializeFieldCalc();
    }//GEN-LAST:event_jButtonMultiplyActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        // TODO add your handling code here:
        if(verifyPendingOperation()){
            SolveOperation();
        }
        
        jLabelOperation.setText("div");
        jTextFieldCalcPast.setText(jTextFieldCalc.getText());
        initializeFieldCalc();
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSquareActionPerformed
        // TODO add your handling code here:
        if(verifyPendingOperation()){
            SolveOperation();
        }
        initializeLabelOperation();
        initializeFieldCalcPast();
        jTextFieldCalc.setText(calculator.Square(Double.parseDouble(jTextFieldCalc.getText())) + "");
    }//GEN-LAST:event_jButtonSquareActionPerformed

    private void jButtonSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSquareRootActionPerformed
        // TODO add your handling code here:
        if(verifyPendingOperation()){
            SolveOperation();
        }
        initializeLabelOperation();
        initializeFieldCalcPast();
        jTextFieldCalc.setText(calculator.SquareRoot(Double.parseDouble(jTextFieldCalc.getText())) + "");
    }//GEN-LAST:event_jButtonSquareRootActionPerformed

    private void jButtonMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoryActionPerformed
        // TODO add your handling code here:
        double numberOnScreen = Double.parseDouble(jTextFieldCalc.getText());
        calculator.FunctionMemory(numberOnScreen);
        jLabelMemoryValue.setText(numberOnScreen + "");
    }//GEN-LAST:event_jButtonMemoryActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        calculator.FunctionMemory_plus(Double.parseDouble(jTextFieldCalc.getText()));
        jLabelMemoryValue.setText(calculator.FunctionMemory_recall() + "");
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMemoryMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoryMinusActionPerformed
        // TODO add your handling code here:
        calculator.FunctionMemory_minus(Double.parseDouble(jTextFieldCalc.getText()));
        jLabelMemoryValue.setText(calculator.FunctionMemory_recall() + "");
    }//GEN-LAST:event_jButtonMemoryMinusActionPerformed

    private void jButtonMemoryRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoryRecallActionPerformed
        // TODO add your handling code here:
        jTextFieldCalc.setText(calculator.FunctionMemory_recall() + "");
    }//GEN-LAST:event_jButtonMemoryRecallActionPerformed

    private void jButtonMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoryClearActionPerformed
        // TODO add your handling code here:
        calculator.FunctionMemory_clear();
        jLabelMemoryValue.setText(calculator.FunctionMemory_recall() + "");
    }//GEN-LAST:event_jButtonMemoryClearActionPerformed

    private void addTextToFieldCalc(String text){
        jTextFieldCalc.setText(jTextFieldCalc.getText() + text);
    }
    
    private void initializeFieldCalc(){
        jTextFieldCalc.setText("0");
    }
    
    private void initializeFieldCalcPast(){
        jTextFieldCalcPast.setText("0");
    }
    
    private void initializeLabelOperation(){
        jLabelOperation.setText("...");
    }
    
    private boolean verifyPendingOperation(){
        
        if(jLabelOperation.getText().equals("...")){
            return false;
        }
        
        return true;
    }
    
    private void SolveOperation(){
        double numberOfCalcField = Double.parseDouble(jTextFieldCalc.getText());        
        double numberOfCalcPastField = Double.parseDouble(jTextFieldCalcPast.getText());
        switch(jLabelOperation.getText()){
            
            case "+":
                jTextFieldCalc.setText(calculator.Add(numberOfCalcPastField, numberOfCalcField) + "");
                break;
            case "-":
                jTextFieldCalc.setText(calculator.Subtract(numberOfCalcPastField, numberOfCalcField) + "");
                break;
            case "X":
                jTextFieldCalc.setText(calculator.Multiply(numberOfCalcPastField, numberOfCalcField) + "");
                break;
            case "div":
                jTextFieldCalc.setText(calculator.Divide(numberOfCalcPastField, numberOfCalcField) + "");
                break;
            default:
                break;
        }
        
        initializeLabelOperation();
        initializeFieldCalcPast();
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClearError;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonMemory;
    private javax.swing.JButton jButtonMemoryClear;
    private javax.swing.JButton jButtonMemoryMinus;
    private javax.swing.JButton jButtonMemoryRecall;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonSquare;
    private javax.swing.JButton jButtonSquareRoot;
    private javax.swing.JButton jButtonSubtract;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JLabel jLabelCalc;
    private javax.swing.JLabel jLabelMemory;
    private javax.swing.JLabel jLabelMemoryValue;
    private javax.swing.JLabel jLabelOperation;
    private javax.swing.JPanel jPanelCalc;
    private javax.swing.JTextField jTextFieldCalc;
    private javax.swing.JTextField jTextFieldCalcPast;
    // End of variables declaration//GEN-END:variables
}
